name: Deployments

on:
  push:
    tags:
      - "*"

concurrency: production

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend
        run: |
          npm ci
          REACT_APP_VERSION=$VERSION npm run build
          mv build ../frontend_build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend_build
          retention-days: 1

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend_build

      - name: Deploy Frontend to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: "frontend_build/"
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
