name: Test CI
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "front/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Paris"
      - uses: actions/checkout@v4
      - name: Install modules
        run: cd front && npm i --only-dev
      - name: Run lint
        run: cd front && npm run lint:ci
      - name: Removes dead code
        run: cd front && npm run deadcode:ci
      - name: Check if package.json is sorted
        run: |
          cd front && npm run sort-package:check
          if [ $? -eq 0 ]; then
            echo "Package.json is sorted correctly."
          else
            exit 1
          fi
      - name: Depcheck
        run: |
          cd front && npm i -g depcheck && npm run depcheck:ci
