name: Update package.json version on tag

on:
  push:
    tags:
      - "*"

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update package.json version
        uses: BellCubeDev/update-package-version-by-release-tag@v2
        with:
          version: ${{ github.ref_name }}

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Update package.json version to ${{ github.ref_name }}"
          git push origin main --force
